
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C100, LENGTH = 0x3F00
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x78000;
C_L1L3_0_buff_0 = .;
. += 0x100;
. = 0x7C000;
C_L1L3_0_buff_1 = .;
. += 0x100;
. = 0x72400;
B_L3L1_0_cons_buff_0 = .;
. += 0x100;
. = 0x70400;
A_L3L1_0_cons_buff_0 = .;
. += 0x2000;
. = 0x74000;
A_L3L1_0_cons_buff_1 = .;
. += 0x2000;
  .bss : { *(.bss*) } > data
}
INPUT(spike2gemv_fused.mlir.prj/op1_gemv_128k_64vs.o)
PROVIDE(main = core_0_2);
